delimiter |
create procedure SP_ENTREES_SELECT
(
	IN NumB INT,
	IN DATEB DATE,
	IN NOMF VARCHAR(50),
	IN idcre INT,
	IN idup INT,
	IN dtcre DATE,
	IN dtup DATE
)
BEGIN
	SELECT * FROM Entrees

	WHERE NumBord LIKE CASE WHEN NumB IS NULL THEN '%' ELSE CAST(NumB AS CHAR) END AND
	DateBord LIKE CASE WHEN DATEB IS NULL THEN '%' ELSE CONCAT('%',CONCAT(CAST(DATEB AS CHAR),'%')) END OR DateBord IS NULL AND
	NomFsseur LIKE CASE WHEN NOMF IS NULL THEN '%' ELSE CONCAT('%',CONCAT(NOMF,'%')) END OR NomFsseur IS NULL AND
	IdCreateur LIKE CASE WHEN idcre IS NULL THEN '%' ELSE CAST(idcre AS CHAR) END AND
	IdModificateur LIKE CASE WHEN idup IS NULL THEN '%' ELSE CAST(idup AS CHAR) END AND
	DateCreation LIKE CASE WHEN dtcre IS NULL THEN '%' ELSE CONCAT('%',CONCAT(CAST(dtcre AS CHAR),'%')) END AND
	DateModification LIKE CASE WHEN dtup IS NULL THEN '%' ELSE CONCAT('%',CONCAT(CAST(dtup AS CHAR),'%')) END;
END|